# Site settings
title: Cal Poly HKN
email: hkn.calpoly@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "/hkn.calpoly.edu"
url: "http://yourdomain.com"
#twitter_username: jekyllrb
github_username:  CalPolyHKN

# Build settings
markdown: kramdown
permalink: pretty

# Github Pages
highlighter: pygments
